name: docker-services-step-ca

networks:
  composes-frontend:
    external: true

services:
  app:
    image: smallstep/step-ca:0.29.0
    restart: unless-stopped
    networks:
      composes-frontend:
        aliases:
          - step-ca-app-container
    healthcheck:
      test: step ca health --ca-url=https://step-ca-app-container 2>/dev/null | grep '^ok' >/dev/null
      start_period: 300s
      start_interval: 3s
      timeout: 5s
      interval: 1800s
      retries: 3
    volumes:
      - type: bind
        source: ./assets/step
        target: /home/step
        bind:
          create_host_path: false
      - type: bind
        source: ../proxy/assets/certs/server
        target: /work/certs/server
        bind:
          create_host_path: true
    environment:
      - TZ=Asia/Tokyo
